### ISSUE TITLE
速度有起飞的么？？我的还是慢。

### ISSUE THREAD

**Issue by lisztomania-Zero** [TkzcM/pandownload-fake-server#11]
![image](https://user-images.githubusercontent.com/50130180/79430662-dc6ef700-7ffb-11ea-97d0-3d1d468ca09c.png)

**Comment by kevinmattew** [comment]
svip表示200m跑满

**Comment by lisztomania-Zero** [comment]
> svip表示200m跑满

![image](https://user-images.githubusercontent.com/50130180/79431305-d62d4a80-7ffc-11ea-84aa-cbde58eae145.png)

**Comment by ldyivan** [comment]
确实是没速度

**Comment by kevinmattew** [comment]
> > svip表示200m跑满
> 
> ![image](https://user-images.githubusercontent.com/50130180/79431305-d62d4a80-7ffc-11ea-84aa-cbde58eae145.png)

本来就是，我用官方下载，在学校的网速就跑不满

**Comment by kevinmattew** [comment]
![捕获](https://user-images.githubusercontent.com/36357431/79435554-6621c300-8002-11ea-9e03-0c753eeab12c.JPG)

**Comment by 935714648** [comment]
user is not authorized, hitcode:118是什么原因？

**Comment by TkzcM** [comment]
不解答下载有关问题，因为我无法修改程序本体
