### ISSUE TITLE
想问一下自己服务器怎么搭建

### ISSUE THREAD

**Issue by kevinmattew** [TkzcM/pandownload-fake-server#12]
直接放在websevers根目录码

**Comment by qipengwang** [comment]
思路是搭建个webServer然后重定向一下服务器，但是别的版本panDown是不能用的，不知道怎么搞，也想自己搭个本地服务器

**Comment by TkzcM** [comment]
https://github.com/TkzcM/pandownload-fake-server/commit/63d32c1e4888e689a8c419d4f32981284fcbb34f
放根目录即可
