### ISSUE TITLE
实测卡在更新脚本然后退出

### ISSUE THREAD

**Issue by unikevin** [TkzcM/pandownload-fake-server#2]
![image](https://user-images.githubusercontent.com/63285034/79413137-b6385f80-7fd9-11ea-8ff5-eaabd46fd005.png)

**Comment by TkzcM** [comment]
https://github.com/TkzcM/pandownload-fake-server/blob/master/PanDownload_add_temp.zip
请下载这个版本

**Comment by unikevin** [comment]
我手动修改了下json，成功打开
