### ISSUE TITLE
百度必死！

### ISSUE THREAD

**Issue by YanShuHao314** [TkzcM/pandownload-fake-server#20]
失去双亲的百度必死!FxxK BAIDU！！！！！！！！

**Comment by Huijing-Y** [comment]
FxxK Baidu + Baidu马甲刘某

**Comment by TkzcM** [comment]
#25

**Comment by 2656** [comment]
FxxK Baidu + Baidu马甲刘某

**Comment by UFOAlastor** [comment]
We do not forgive
　　我们不会原谅

We do not forget
　　我们不会忘记
