### ISSUE TITLE
是否可以做成openwrt插件挂到路由器上面

### ISSUE THREAD

**Issue by russellcoinpay** [TkzcM/pandownload-fake-server#21]
是否可以做成openwrt插件挂到路由器上面，然后离线下载到路由器的u盘啥的，或者直接电脑上面有个客户端直接连接路由器的服务端，进行下载，这样又可以离线，又可以本地

**Comment by TkzcM** [comment]
可以使用远程aria2功能

**Comment by createskyblue** [comment]
我丢到了openwrt的www目录下，然后路由器dns重定向
