### ISSUE TITLE
在线更新失败

### ISSUE THREAD

**Issue by Sniper970119** [TkzcM/pandownload-fake-server#22]
我把host改了，也挂了梯子，但是依然显示“文件校验失败”，并且手动下载的版本也显示这个。

**Comment by TkzcM** [comment]
更新只是公告用的，不影响使用，如果不喜欢我可以去掉

**Comment by Sniper970119** [comment]
> 
> 
> 更新只是公告用的，不影响使用，如果不喜欢我可以去掉

但是速度依然是200kbs左右，是现在已经没办法加速了吗

**Comment by TkzcM** [comment]
> > 更新只是公告用的，不影响使用，如果不喜欢我可以去掉
> 
> 但是速度依然是200kbs左右，是现在已经没办法加速了吗

下载相关的问题我无法解决

**Comment by Sniper970119** [comment]
> 
> 
> > > 更新只是公告用的，不影响使用，如果不喜欢我可以去掉
> > 
> > 
> > 但是速度依然是200kbs左右，是现在已经没办法加速了吗
> 
> 下载相关的问题我无法解决

哦哦   谢谢啦
