### ISSUE TITLE
用pd都别用大号,现在bd钓鱼封号

### ISSUE THREAD

**Issue by CberYellowstone** [TkzcM/pandownload-fake-server#28]

**Comment by zgcwkj** [comment]
为什么这样说？怎么确定是 bd 钓鱼呢？

**Comment by CberYellowstone** [comment]
> 为什么这样说？怎么确定是 bd 钓鱼呢？

昨天到今天早上有一段时间是进不去的,会提示服务器错误0x1c
而现在就算不用这个项目也能直接进去
但是现在不能不登录百度账号使用,正常的pd是可以不登录直接下载分享链接的
而且捐赠二维码的支付宝姓名也变了
已经有很多吧友被封了
用的话还是谨慎点吧

**Comment by zgcwkj** [comment]
> > 为什么这样说？怎么确定是 bd 钓鱼呢？
> 
> 昨天到今天早上有一段时间是进不去的,会提示服务器错误0x1c
> 而现在就算不用这个项目也能直接进去
> 但是现在不能不登录百度账号使用,正常的pd是可以不登录直接下载分享链接的
> 而且捐赠二维码的支付宝姓名也变了
> 已经有很多吧友被封了
> 用的话还是谨慎点吧

好的！！！

**Comment by AnonAlpha** [comment]
确实，pandownload.com的https证书已经被去掉了，肯定有问题

**Comment by TkzcM** [comment]
#25 
目前没看到有封号的
提取码查询的服务器开着，个人觉得可能在取证或有他人接手
