### ISSUE TITLE
我想问一下可以搭本地服务器来实现吗

### ISSUE THREAD

**Issue by mixli** [TkzcM/pandownload-fake-server#3]
具体是怎么操作的啊，如果大佬的服务器不用了我想知道不能拿做个本地服务器来重定向，可以讲述一下吗
### 感谢大佬的分享

**Comment by TkzcM** [comment]
pandownload-fake-server.zip 为服务器需要的文件
nginx 配置 server_name pandownload.com
hosts 修改为本地服务器IP

**Comment by lisztomania-Zero** [comment]
![image](https://user-images.githubusercontent.com/50130180/79420797-3a93de00-7fec-11ea-8125-de98e46e8fa7.png)
没辙啊？？

**Comment by oliver-csu** [comment]
> ![image](https://user-images.githubusercontent.com/50130180/79420797-3a93de00-7fec-11ea-8125-de98e46e8fa7.png)
> 没辙啊？？

或许要加钱

**Comment by lisztomania-Zero** [comment]
> > ![图片](https://user-images.githubusercontent.com/50130180/79420797-3a93de00-7fec-11ea-8125-de98e46e8fa7.png)
> > 没辙啊？？
> 
> 或许要加钱

还是不能起飞。

**Comment by qipengwang** [comment]
> pandownload-fake-server.zip 为服务器需要的文件
> nginx 配置 server_name pandownload.com
> hosts 修改为本地服务器IP

panDown应该不需要修改吧，仅仅需要配置一下服务器？

**Comment by k652** [comment]
![image](https://user-images.githubusercontent.com/40596628/79439041-f104bc80-8006-11ea-9e36-cf730ca7d54f.png)
哎，问一下，浏览器能打开了，pd怎么还是接受数据失败哦，解压的api已经放到根目录了

**Comment by hhb0206** [comment]
> > > ![图片](https://user-images.githubusercontent.com/50130180/79420797-3a93de00-7fec-11ea-8125-de98e46e8fa7.png)
> > > 没辙啊？？
> > 
> > 
> > 或许要加钱
> 
> 还是不能起飞。

很多人想用pandownload的客户端。 只是pd的盘搜和加速都没了。心疼

**Comment by candyyjs** [comment]
度盘搜真的好用啊

**Comment by candyyjs** [comment]
> 
> 
> > > > ![图片](https://user-images.githubusercontent.com/50130180/79420797-3a93de00-7fec-11ea-8125-de98e46e8fa7.png)
> > > > 没辙啊？？
> > > 
> > > 
> > > 或许要加钱
> > 
> > 
> > 还是不能起飞。
> 
> 很多人想用pandownload的客户端。 只是pd的盘搜和加速都没了。心疼

度盘搜真的好用啊

**Comment by ccp-dad** [comment]
等大佬破解加速原理

**Comment by TkzcM** [comment]
> 等大佬破解加速原理

速度问题不解决也无法解决
