### ISSUE TITLE
关于更新

### ISSUE THREAD

**Issue by tangli159** [TkzcM/pandownload-fake-server#30]
谢谢您的项目，不过点开都会提示要更新到4.04版本。理解您想要纪念，但是可能有的人不太懂。我没点在线更新，不知道点了是啥后果哈。我点了手动，弹到您的项目主页，懂的人自然就懂了。所以建议楼主可以在弹窗文字说明里面写不要更新之类的~，仅仅是个建议哈~求轻拍

**Comment by tangli159** [comment]
当然了pd里面本来就提供取消检测更新选项，也不影响什么~

**Comment by RefinedMe** [comment]
为啥下载的时候一直卡在连接资源...

**Comment by tangli159** [comment]
> 为啥下载的时候一直卡在连接资源...

我没出现诶

**Comment by TkzcM** [comment]
fixed
