### ISSUE TITLE
大佬，求教能进软件，无法现在，提示获取链接失败

### ISSUE THREAD

**Issue by linuxu2015** [TkzcM/pandownload-fake-server#31]
大佬，求教能进软件，无法下载，提示获取链接失败
每次点下载都会有post请求
![image](https://user-images.githubusercontent.com/12248480/79524091-31f5e300-8092-11ea-9b4d-624548bdb428.png)
会提示下载失败
![image](https://user-images.githubusercontent.com/12248480/79524133-4934d080-8092-11ea-86a5-c334450ff175.png)

**Comment by linuxu2015** [comment]
用的是github上的PanDownload.exe

**Comment by TkzcM** [comment]
无法复现，能说说具体步骤吗

或者多换几个下载方式，重新登录

**Comment by Creeper666** [comment]
我用的是吾爱的pd，没有问题
