### ISSUE TITLE
本地搭建fake-server问题

### ISSUE THREAD

**Issue by nbdboy** [TkzcM/pandownload-fake-server#32]
昨晚在玩客云上搭的fake-server还能用的，路由器上Dnsmasq将pandownload重定向了本地ip
今早上再试就不行了，然后有换成最新的fake-server还是不行，不知道是哪的问题
![image](https://user-images.githubusercontent.com/47210818/79525008-797d6e80-8094-11ea-9851-017585d16c27.png)

**Comment by TkzcM** [comment]
排除法，如果换成我提供的IP可以用，就是本地服务器的问题
可以试试直接访问能否打开

**Comment by nbdboy** [comment]
> 排除法，如果换成我提供的IP可以用，就是本地服务器的问题
> 
> 可以试试直接访问能否打开

用你的ip也不行，我自己琢磨去了

**Comment by nbdboy** [comment]
我把路由器上的ssr关了后就好了，看来是冲突了

**Comment by nbdboy** [comment]
不对，是windows上哪个软件冲突了，手机就可以访问

**Comment by Ljh554992** [comment]
> 不对，是windows上哪个软件冲突了，手机就可以访问

电脑上是不是有什么翻墙代理的软件？

**Comment by nbdboy** [comment]
> > 不对，是windows上哪个软件冲突了，手机就可以访问
> 
> 
> 
> 电脑上是不是有什么翻墙代理的软件？

电脑也可以访问，就是启动不了，错误1，奇怪了，没有任何代理软件

**Comment by BerialJ** [comment]
速度慢呢？被封号了吗

**Comment by nbdboy** [comment]
已解决，本地问题
