### ISSUE TITLE
一些猜测

### ISSUE THREAD

**Issue by TkzcM** [TkzcM/pandownload-fake-server#36]
目前 pandownload.com 除中国大陆地区外均解析到 CloudFlare 节点，**（以下存疑）该 CloudFlare 节点的源站昨晚使用了本项目的相关文件，并修改了捐款码**，现在已显示维护，个人认为是原作者在 CloudFlare 删除域名后被有心之人趁虚而入。
而大陆地区解析到的腾讯云 IP 有可能为百度公司所有。与原 /api/latest 文件对比，腾讯云的版本新增了强制升级，且在线更新地址 dl1.cnponer.com 已指向百度的 IP。
因此，个人不推荐在不修改 Hosts 的情况下使用 PanDownload，也请使用 Hosts 指向 127.0.0.1 屏蔽提取码查询等请求。
```
127.0.0.1 search.pandown.cn
127.0.0.1 pandown.cn
```

**以上都是我随便说的，我也不知道。**

**Comment by by-FLY** [comment]
老哥nb奥fk百度

**Comment by liuhaidong22125** [comment]
是不是在暗示百度在钓鱼？

**Comment by ThebestkillerTBK** [comment]
可以访问了（弹出了cloudflare检查）出来维护中，但过一会变垃圾广告了，这是你所谓国外访问吗

**Comment by RuytzzZ** [comment]
我刚才还能打开 关了就打不开了，有个下载的跳到这了 我还以为谁拿到服务器了

**Comment by Os-glthub** [comment]
![TIM截图20200417183503](https://user-images.githubusercontent.com/52124855/79560473-41008380-80da-11ea-8c95-dfd2a6d08a9b.png)
添加以下hosts后如上图。hosts保留64.52.84.68 pandownload.com也未恢复/
127.0.0.1 search.pandown.cn
127.0.0.1 pandown.cn

**Comment by TkzcM** [comment]
> 添加以下hosts后如上图。hosts保留64.52.84.68 pandownload.com也未恢复/
> 127.0.0.1 search.pandown.cn
> 127.0.0.1 pandown.cn

试试本地服务器/脚本缓存版 已确认启动时不会访问这两个域名

**Comment by barnett2010** [comment]
确实有这个情况，我昨晚0点刷新官网突然看到官网直接放了api文件。和python脚本，就心有疑虑。然后保存文件。对比了一下。有改动

**Comment by susanbushisan** [comment]
我这边可以直连上PDL，没有进行任何操作，另外dl1.cnponer.com现在貌似指向的是阿里云的地址。修改hosts后也没有弹出接收数据失败，至于二维码，我这边没有之前的数据无法判断

**Comment by ThebestkillerTBK** [comment]
> 确实有这个情况，我昨晚0点刷新官网突然看到官网直接放

> 确实有这个情况，我昨晚0点刷新官网突然看到官网直接放了api文件。和python脚本，就心有疑虑。然后保存文件。对比了一下。有改动

你把那些文件传到github上

**Comment by bobi83** [comment]
cnponer.com is one of the developer

**Comment by SadTomlzr** [comment]
现在百度浏览地址里面访问的pandownload.com不是https是http。捐助界面是能打开的。但是你从以前的软件来看，这个是打不开的。从以前软件来打开
![image](https://user-images.githubusercontent.com/43662748/79628191-6a202300-8171-11ea-907e-f6bbc1dbeb32.png)
是这样的链接 ：https://pandownload.com/donate.html
但是浏览器里面访问是这样的链接
http://pandownload.com/
我不知道出了什么问题。但是我觉得不应该相信官网！直到作者出来澄清！不然我觉得我们可能会支持错对象

**Comment by UFOAlastor** [comment]
贴吧上有人发帖表示账号被冻结[https://tieba.baidu.com/p/6621848863#131549627098l](https://tieba.baidu.com/p/6621848863#131549627098l)
可能和百度钓鱼相关。
还有我想知道使用替代服务器，有没有可能被百度检测出来？

**Comment by TkzcM** [comment]
> 贴吧上有人发帖表示账号被冻结https://tieba.baidu.com/p/6621848863#131549627098l
> 可能和百度钓鱼相关。
> 还有我想知道使用替代服务器，有没有可能被百度检测出来？

目前除了这个没有看到其他封号的用户，也无法确定是因为使用了 PanDownload 而封号
