### ISSUE TITLE
pd启动成功，速度还是bd，，，

### ISSUE THREAD

**Issue by BerialJ** [TkzcM/pandownload-fake-server#37]
原本非pd用户，看了新闻感觉逛逛git会有惊喜。。。
本地server搭成了，mobaxterm搭了一次，换nginx又试了一次。。。
为什么速度还是熟悉的味道【掀桌子】

再去试试burp能不能重放百度的试用加速模式包。。。

**Comment by ThebestkillerTBK** [comment]
用fakeserver应该会加速

**Comment by TkzcM** [comment]
不解答下载有关问题
fake-server 无加速功能
