### ISSUE TITLE
大佬，我修改了host还是进不去软件

### ISSUE THREAD

**Issue by 1530531503** [TkzcM/pandownload-fake-server#4]
提示接受数据失败
![image](https://user-images.githubusercontent.com/56064007/79420765-29e36800-7fec-11ea-8d24-664f7a95b078.png)

**Comment by Werner9** [comment]
你是不是修改了环境变量里的代理？要把删掉才能用。。

**Comment by avsba001** [comment]
我也是，然后把api放自己群辉里搞好了

**Comment by TkzcM** [comment]
服务器在境外且为低价机，连通性可能不太好

**Comment by CryoSky** [comment]
借楼问一下环境变量里的代理是具体什么名称呀？我也是同样问题但是我查了自己的环境变量没看到奇怪的名称（WIN10）

**Comment by reimurin** [comment]
你好，我也有这种问题，最后发现是代理服务器的问题，把代理服务器关闭就可以正常进去了。

**Comment by lyj0309** [comment]
不行啊，ssr啥的全关了，也打不开，直接访问ip也是访问不了

**Comment by reimurin** [comment]
> 不行啊，ssr啥的全关了，也打不开，直接访问ip也是访问不了

那你试试我在国内服务器上搭建的服务
hosts文件那一行改为
pan.732.ac.cn pandownload.com
用这个试一试。

**Comment by Guyao146** [comment]
> > 不行啊，ssr啥的全关了，也打不开，直接访问ip也是访问不了
> 
> 那你试试我在国内服务器上搭建的服务
> hosts文件那一行改为
> pan.732.ac.cn pandownload.com
> 用这个试一试。

老哥，我在北京有个服务器，时间差不多还有半年，能用做这个吗，我也想搭一个

**Comment by reimurin** [comment]
> > > 不行啊，ssr啥的全关了，也打不开，直接访问ip也是访问不了
> > 
> > 
> > 那你试试我在国内服务器上搭建的服务
> > hosts文件那一行改为
> > pan.732.ac.cn pandownload.com
> > 用这个试一试。
> 
> 老哥，我在北京有个服务器，时间差不多还有半年，能用做这个吗，我也想搭一个

可以啊

**Comment by Guyao146** [comment]
> > > > 不行啊，ssr啥的全关了，也打不开，直接访问ip也是访问不了
> > > 
> > > 
> > > 那你试试我在国内服务器上搭建的服务
> > > hosts文件那一行改为
> > > pan.732.ac.cn pandownload.com
> > > 用这个试一试。
> > 
> > 
> > 老哥，我在北京有个服务器，时间差不多还有半年，能用做这个吗，我也想搭一个
> 
>
刚刚转发了一个老哥的，感觉还行

**Comment by Ghjk94522** [comment]
> > 不行啊，ssr啥的全关了，也打不开，直接访问ip也是访问不了
> 
> 那你试试我在国内服务器上搭建的服务
> hosts文件那一行改为
> pan.732.ac.cn pandownload.com
> 用这个试一试。

老哥，请问是自己有服务器就可以搭嘛，能不能简单说一下怎么搭（我有服务器了

**Comment by reimurin** [comment]
> > > 不行啊，ssr啥的全关了，也打不开，直接访问ip也是访问不了
> > 
> > 
> > 那你试试我在国内服务器上搭建的服务
> > hosts文件那一行改为
> > pan.732.ac.cn pandownload.com
> > 用这个试一试。
> 
> 老哥，请问是自己有服务器就可以搭嘛，能不能简单说一下怎么搭（我有服务器了

你需要搭建一个web环境

**Comment by Guyao146** [comment]
> > > 不行啊，ssr啥的全关了，也打不开，直接访问ip也是访问不了
> > 
> > 
> > 那你试试我在国内服务器上搭建的服务
> > hosts文件那一行改为
> > pan.732.ac.cn pandownload.com
> > 用这个试一试。
> 
> 老哥，请问是自己有服务器就可以搭嘛，能不能简单说一下怎么搭（我有服务器了

你先得有一台服务器
部署环境的话我推荐你用宝塔
然后另外一个issue有老哥的正确安装方法
