### ISSUE TITLE
抵制baidu, 从我做起

### ISSUE THREAD

**Issue by gongyuzicong** [TkzcM/pandownload-fake-server#41]
从此不再购买百度网盘SVIP服务, 搜索引擎改成bing, 路由器装插件屏蔽baidu广告

**Comment by jcq15** [comment]
也可以用买svip的钱买个梯子，用Google

**Comment by jerryasmr18** [comment]
这个很难避免，我们自身不使用百度产品，但是其他人给我们分享文件大概率还是用的百度云，真的有点心有余而力不足的感觉。类似的情况还有腾讯，大家都知道QQ微信监管严格，侵犯隐私，但是用户群实在是太大了，不得不用。

最近发现一个云盘系统Cloudreve，使用体验非常棒，只是需要自己搭建，功能上大于百度网盘，有时间大家可以倒腾一下。

**Comment by TkzcM** [comment]
#25
