### ISSUE TITLE
请问自建服务器如何部署

### ISSUE THREAD

**Issue by Dreammer12138** [TkzcM/pandownload-fake-server#42]
我有一个树莓派，想把这个脚本部署在树莓派上，方便的话可以写一个本地部署的教程吗，谢谢大佬

**Comment by JoeLee-TQXTC** [comment]
我其实，，，已经摸出了台3B+。。。准备折腾折腾试试，，，不过我还是大学在读，，，最近可能没有时间去实现这个项目。。。。目前还在为了绩点挣扎（笑），等这段时期过去，有时间了我一定会去尝试一下，去折腾的。（保证在毕业之前会做哒）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dreammer12138"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 中午11:37
收件人:&nbsp;"TkzcM/pandownload-fake-server"<pandownload-fake-server@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[TkzcM/pandownload-fake-server] 请问自建服务器如何部署 (#42)





 
我有一个树莓派，想把这个脚本部署在树莓派上，方便的话可以写一个本地部署的教程吗，谢谢大佬

**Comment by TkzcM** [comment]
安装nginx
把配置文件放到 /etc/nginx/conf.d
把 fake-server.zip 里的文件放到 /home/pandownload
done

**Comment by Guyao146** [comment]
> 安装nginx
> 把配置文件放到 /etc/nginx/conf.d
> 把 fake-server.zip 里的文件放到 /home/pandownload
> done

你好，我现在已经把东西都放好了，访问我服务器ip也能跳转到bdlogin，但就是pdl接受数据失败

**Comment by TkzcM** [comment]
> 你好，我现在已经把东西都放好了，访问我服务器ip也能跳转到bdlogin，但就是pdl接受数据失败

修改 Hosts 后，手动访问 /api/init 检查是否返回正常
或者看看 nginx 的 log 有没有 pd 的访问记录

**Comment by Guyao146** [comment]
> > 你好，我现在已经把东西都放好了，访问我服务器ip也能跳转到bdlogin，但就是pdl接受数据失败
> 
> 修改 Hosts 后，手动访问 /api/init 检查是否返回正常
> 或者看看 nginx 的 log 有没有 pd 的访问记录

好的，我试试，端口只能用80吗

**Comment by TkzcM** [comment]
> 好的，我试试，端口只能用80吗

是的

**Comment by Guyao146** [comment]
> > 好的，我试试，端口只能用80吗
> 
> 是的

主要是我就一学生，没法备案服务器，这么说的话我可能不能搞了
我们群里也有一个大佬搞上了，是国内的服务器
刚刚连了一下感觉速度还不错
