### ISSUE TITLE
我有一个完备的服务器软件（建议加入一些东西）

### ISSUE THREAD

**Issue by Sun-ZhenXing** [TkzcM/pandownload-fake-server#43]
[fakserver.zip](https://github.com/TkzcM/pandownload-fake-server/files/4496038/fakserver.zip)
就是这个
![image](https://user-images.githubusercontent.com/44517244/79628012-ac486500-816f-11ea-8472-6853f5ad2ad9.png)
构建起pandownload.com一步到位
![image](https://user-images.githubusercontent.com/44517244/79628028-e1ed4e00-816f-11ea-8efc-84b447691fa5.png)

**Comment by Sun-ZhenXing** [comment]
个人建议，把 webs.exe 这个文件加入项目，这样不管什么水平的人都能傻瓜式运行服务，599KB也不大。

**Comment by ccicnce113424** [comment]
> 个人建议，把 webs.exe 这个文件加入项目，这样不管什么水平的人都能傻瓜式运行服务，599KB也不大。

webs.exe会自动修改hosts吗

**Comment by susanbushisan** [comment]
你直接pullrequest啊，这个原理是改本地host吗？

**Comment by Sun-ZhenXing** [comment]
不是，这是个文件服务器，修改hosts的命令在文件夹里面，管理员权限运行就可以了

**Comment by TkzcM** [comment]
https://github.com/zgcwkj/PanDownloadOpen
已经有一键的啦

**Comment by Sun-ZhenXing** [comment]
> https://github.com/zgcwkj/PanDownloadOpen
> 已经有一键的啦
> 没有原来的后端，添加文件也没什么用
也对，不太了解C#
不懂已经写了一个自动修改的程序
但是你觉得pand作者会拿什么写这个服务器，这个功能已经可以了吧

**Comment by TkzcM** [comment]
> > 也对，不太了解C#
> > 不懂已经写了一个自动修改的程序
> > 但是你觉得pand作者会拿什么写这个服务器，这个功能已经可以了吧

本项目目前只为了能正常打开软件，所以尽量保持轻量
