### ISSUE TITLE
分享我自己写的一个超级工具箱的bat

### ISSUE THREAD

**Issue by Guyao146** [TkzcM/pandownload-fake-server#46]
本人纯小白，为了给比我更小白的hxd萌可以快点使用所以我写了这个脚本
hosts修改功能 win7以下的系统禁用了，所以如果xp之类的系统想用的话联系我吧
https://sakuragu.lanzous.com/b01z5b4if 密码:5g59
脚本纯免费哈

**Comment by Guyao146** [comment]
打开以后自动将新服务器的hosts添加进去

**Comment by Su520** [comment]
giao？

**Comment by Guyao146** [comment]
> giao？

哈？
