### ISSUE TITLE
http请求错误 0x1c

### ISSUE THREAD

**Issue by dengshopping** [TkzcM/pandownload-fake-server#47]
![Snipaste_2020-04-18_23-18-32](https://user-images.githubusercontent.com/63917300/79641570-f27ee200-81ca-11ea-88a2-261cb6c02f31.png)
ru't
![Snipaste_2020-04-18_23-19-28](https://user-images.githubusercontent.com/63917300/79641601-2528da80-81cb-11ea-89ea-63c690c64091.png)
如图，添加hosts后出现了这种问题...我是真的萌新，才入GitHub，望各位大佬求解
http请求错误 0x1c
（可能这问题过于萌新了）

**Comment by TheInterestingSoul** [comment]
看看dns缓存刷新了没
两种办法
1. 重启
2. 打开cmd输入
```bat
ipconfig /flushdns
```

**Comment by TheInterestingSoul** [comment]
另外readme那个host，作者说连通性不好，试试 #4 里 @reimurin 这个
```hosts
pan.732.ac.cn pandownload.com
```

**Comment by dengshopping** [comment]
> 另外readme那个主持人，作者说连通性不好，试试[＃4](https://github.com/TkzcM/pandownload-fake-server/issues/4)里@reimurin这个
> 
> ```
> pan.732.ac.cn pandownload.com
> ```

感谢了，换成pan.732.ac.cn成功了，可能真的连通性不好吧23333
