### ISSUE TITLE
关于劫持

### ISSUE THREAD

**Issue by TkzcM** [TkzcM/pandownload-fake-server#49]
255

**Comment by Dustsc** [comment]
已转，正在审核

**Comment by RuytzzZ** [comment]
最开始 你的文件里  有那个4.04的升级信息吗 点击手动更新 就跳到这个项目主页？

**Comment by TkzcM** [comment]
> 最开始 你的文件里 有那个4.04的升级信息吗 点击手动更新 就跳到这个项目主页？

恶意劫持者使用了本项目的文件，所以会显示 4.0.4 更新
除了劫持以外，只有修改过 Hosts 的人才会访问 fake-server
更新信息只是为了纪念，没有实际的更新

**Comment by MonianHello** [comment]
> 基本可以确认，在 4.17-4.18 期间有人利用 CloudFlare 劫持了 pandownload.com，且使用的是本项目的文件
> 详见 #36 和 #48
> 当天我看到 #30 后，修改了 64.52.84.68 上的更新提示
> 但没有 commit 到这里
> 所以用来劫持的 Server 非我所有
> 现在劫持已经被修复，全球解析到的都是 118.24.245.110
> 劫持者可能想把锅甩我头上，我该收拾收拾细软跑了
> 
> 我没有 52pojie 账号，希望有人帮我转过去
> https://www.52pojie.cn/thread-1159015-1-1.html

https://www.52pojie.cn/forum.php?mod=viewthread&tid=1160777&page=1&extra=#pid31452730
也只能帮到这了

**Comment by Vurliy** [comment]
现在 http://pandownload.com 可以访问. 各地ping的服务器也不相同. 所以现在这个官网还是假的? 
我修改了host 添加了
64.52.84.68 pandownload.com
127.0.0.1 search.pandown.cn
127.0.0.1 pandown.cn
运行软件后依然提示 4.0.4 更新, 这样正常么?
