### ISSUE TITLE
不知道为什么，修改host可以打开软件但是不能登录

### ISSUE THREAD

**Issue by orangeff** [TkzcM/pandownload-fake-server#51]
尝试过用户名登录和扫码登录，都反馈如下错误
![image](https://user-images.githubusercontent.com/42274972/79678119-8764f800-822a-11ea-8aad-64fff1036b78.png)

**Comment by lingying177** [comment]
直接使用cookie登录

**Comment by lingying177** [comment]
> 尝试过用户名登录和扫码登录，都反馈如下错误
> ![image](https://user-images.githubusercontent.com/42274972/79678119-8764f800-822a-11ea-8aad-64fff1036b78.png)

直接使用cookie登录

**Comment by kafuuchino-s** [comment]
我直接用cookie登录也是显示这个错误

**Comment by orangeff** [comment]
> > 尝试过用户名登录和扫码登录，都反馈如下错误
> > ![image](https://user-images.githubusercontent.com/42274972/79678119-8764f800-822a-11ea-8aad-64fff1036b78.png)
> 
> 直接使用cookie登录

我用cookie也出现了这个错误，不知道是怎么回事

**Comment by TkzcM** [comment]
服务器被 CC 了，先用本地版吧
