### ISSUE TITLE
服务自建

### ISSUE THREAD

**Issue by yzddahaoren** [TkzcM/pandownload-fake-server#55]
链接: https://pan.baidu.com/s/18odol_HFD8EmGf7SDovq9w 提取码: 6g7p
- 下载对应平台；解压
- win下双击`bat`文件
- linuxx下`./start.sh` （确保80端口未占用）
- 修改host；
```
win : 127.0.0.1 pandownload.com
lin：YOURHOST pandownload.com
```
**感谢软件作者和pandownload-fake-server**
**祝百度早日被做空，相信也不远了**

**Comment by 1530531503** [comment]
这个有啥用啊

**Comment by wrxx2019** [comment]
小白请教一下，在linux已经有运行caddy的情况下，应该怎么操作？尝试把caddyfile的内容添加到原有caddy的配置中，运行./start.sh会出现如下的提示一闪而过，不能选择y/n. 测试添加host失败不能打开软件。
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you agree to the terms? (y/n)

**Comment by yzddahaoren** [comment]
> 小白请教一下，在linux已经有运行caddy的情况下，应该怎么操作？尝试把caddyfile的内容添加到原有caddy的配置中，运行./start.sh会出现如下的提示一闪而过，不能选择y/n. 测试添加host失败不能打开软件。
> Your sites will be served over HTTPS automatically using Let's Encrypt.
> By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
> https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
> Do you agree to the terms? (y/n)

证书申请失败，caddy会自动退出，因为我是从服务器复制的caddy，版本可能和你的不一样，强制https的话，可尝试添加一行`tls off`即关闭证书申请，但Caddyfile不向下兼容，这个具体还是根据你自己的版本看下官方文档怎么写的。
```
http://pandownload.com {
  root server/
  tls off
}
```
