### ISSUE TITLE
历史版本以及与本仓库关系

### ISSUE THREAD

**Issue by wsdjeg** [TkzcM/pandownload-fake-server#59]
之前就听说过 pandownload，请问这个项目原作者是否在使用 github，跟本仓库又有什么关系，以及此次被抓的到底是不是原作者，还是只是一个利用pandownload牟利的人？

**Comment by Guyao146** [comment]
pdl据其他人说是个开源项目，但我没实际见到过源码，本仓库仅仅是为了存放pandownload可以正常使用的文件，抓的是原作者，pandownload从来没想过盈利，我用了这么长时间没交过一次钱

**Comment by TkzcM** [comment]
https://github.com/Kiry66/ 理论上来说这个是原作者的 GitHub 账号
pandownload 不是开源项目
本项目和 pandownload 原作/原作者没有任何关系

至于抓的是不是原作者，只有网警知道

**Comment by Guyao146** [comment]
> https://github.com/Kiry66/ 理论上来说这个是原作者的 GitHub 账号
> pandownload 不是开源项目
> 本项目和 pandownload 原作/原作者没有任何关系
> 
> 至于抓的是不是原作者，只有网警知道

应该不是吧？aria2和pdl作者还有关系嘛，pdl不就调用aria2下载东西吗

**Comment by wsdjeg** [comment]
网盘下载的工具比较多，之前黑客派网站上貌似也有一个，好像也下架了
