### ISSUE TITLE
一次性大量下载会被百度检测到且限制速度

### ISSUE THREAD

**Issue by AnkoGo** [TkzcM/pandownload-fake-server#61]
###  一次性下载超过几百个文件时候会限制速度，且某些下载会返回403拒绝服务的错误码，望更新！  
![image](https://user-images.githubusercontent.com/58206163/79814099-ffa8f600-83af-11ea-95a9-671e0904182b.png)

**Comment by UFOAlastor** [comment]
这个是一直都有的问题！

**Comment by AnkoGo** [comment]
哦哦，这样啊，可是我冲过很多次的超级vip，是不会限制速度的，满速度下载！望周知！我的意思是，大量下载会被重新验证身份，判断是否是超级vip或者vip!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zander Alastor"<notifications@github.com&gt;; 
发送时间: 2020年4月21日(星期二) 上午9:33
收件人: "TkzcM/pandownload-fake-server"<pandownload-fake-server@noreply.github.com&gt;; 
抄送: "anko"<2930546527@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TkzcM/pandownload-fake-server] 一次性大量下载会被百度检测到且限制速度 (#61)





 
这个是一直都有的问题！

**Comment by TkzcM** [comment]
下载问题无法解决
