### ISSUE TITLE
自建服务器Uginx里配置要怎么填

### ISSUE THREAD

**Issue by ziyouzhiyou** [TkzcM/pandownload-fake-server#64]
server_name 这里是填”pandownload.com www.pandownload.com“还是填自己的域名

**Comment by AnkoGo** [comment]
不用填，直接屏蔽ip然后打开即可

**Comment by ziyouzhiyou** [comment]
> 不用填，直接屏蔽ip然后打开即可
不是，我想自己搭一个，不想直接用64.52.84.68

**Comment by AnkoGo** [comment]
百度查查应该不难



---原始邮件---
发件人: "ziyouzhiyou"<notifications@github.com&gt;
发送时间: 2020年4月21日(周二) 下午3:43
收件人: "TkzcM/pandownload-fake-server"<pandownload-fake-server@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"AnkoGo"<2930546527@qq.com&gt;;
主题: Re: [TkzcM/pandownload-fake-server] 自建服务器Uginx里配置要怎么填 (#64)




  
不用填，直接屏蔽ip然后打开即可
 不是，我想自己搭一个，不想直接用64.52.84.68

**Comment by TkzcM** [comment]
填 pandownload.com www.pandownload.com
