### ISSUE TITLE
百度账号登陆不进去了

### ISSUE THREAD

**Issue by pangci22** [TkzcM/pandownload-fake-server#7]
用cookie也不行，提示获取bdstoken失败

**Comment by TkzcM** [comment]
请暂时使用Cookie登录 晚上会加跳转
获取bdstoken失败为cookie不全

**Comment by RtYkk** [comment]
cookie需要哪些？我记得原来只要一个BDUSS就行了，现在BDUSS=xxxxx好像不对？

**Comment by CoderCore** [comment]
> 
> 
> cookie需要哪些？我记得原来只要一个BDUSS就行了，现在BDUSS=xxxxx好像不对？

BDUSS 和 STOKEN ，这个格式 BDUSS=xxx;STOKEN=xxx

**Comment by jearhe** [comment]
> > cookie需要哪些？我记得原来只要一个BDUSS就行了，现在BDUSS=xxxxx好像不对？
> 
> BDUSS 和 STOKEN ，这个格式 BDUSS=xxx;STOKEN=xxx

我输入这个格式 报bdstoken错误 大佬知道原因吗

**Comment by TkzcM** [comment]
已修复登录
