### ISSUE TITLE
关于修复登录账号的方法

### ISSUE THREAD

**Issue by FlyIWind** [TkzcM/pandownload-fake-server#9]
在init文件中有一项叫做loginurl 您可以制作一个bdlogin.html或者将这项配置改为百度最新的登录地址 这样就可以修复Pandownload内置的登录功能了

**Comment by F-Unction** [comment]
何不自己commit

**Comment by btbsja** [comment]
有 init 文件吗，我居然我没看到

**Comment by TkzcM** [comment]
已修复登录
